---
# tasks file for artifactory-role
- name: fetch repository
  yum_repository:
    name: Artifactory 
    description: ARTIFACTORY
    baseurl: https://releases.jfrog.io/artifactory/artifactory-rpms/
    repo_gpgcheck: yes
    gpgcheck: yes
    gpgkey: https://releases.jfrog.io/artifactory/artifactory-rpms/repodata/repomd.xml.key

- name: install artifactory
  yum:
    name: jfrog-artifactory-oss

- name: launch artifactory
  systemd:
    name: artifactory
    state: started
    enabled: yes
