---
- name: Provision developpers machines
  hosts: dev
  become: yes
  tasks:
  - name: install utilities
    apt:
      update_cache: yes
      name:
      - unzip
      - git
      - nano
      - default-jdk

 - name: install Maven manually
   block:
   - name: download Apache
     unarchive:
       src: https://downloads.apache.org/apache/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
       dest: /opt
       remote_src: yes

- name: export Maven and create Maven.sh
  lineinfile:
    dest: /etc/profile.d/maven.sh
    line: "{{item.line}}"
    create: yes
    with_items:
     - {line: '#! /bin/bash'}
     - {line: 'export M2_HOME=/opt/apache-maven-3.8.1'}
     - {line: 'export M2=$M2_HOME/bin'}
     - {line: 'export PATH=$PATH:$M2'}

- name: export Maven ENV variables
  shell: ". /etc/profile.d/maven.sh"
  register: export_check

- name: debug check task
  debug:
    var: export_check
