---
- name: download Apache Maven
  unarchive:
    src: https://downloads.apache.org/maven/maven-{{ maven_major_version }}/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
    dest: "{{ maven_parent_directory }}"
    remote_src: yes

- name: export Maven and create maven.sh
  lineinfile: 
    path: "{{ maven_profile_location }}"
    line: "{{ item.line }}"
    create: yes
  with_items:
    - { line: '#! /bin/bash' }
    - { line: 'export M2_HOME={{ maven_parent_directory }}/apache-maven-{{ maven_version }}' }
    - { line: 'export M2=$M2_HOME/bin' }
    - { line: 'export PATH=$PATH:$M2' }

- name: add executable rights to maven.sh
  file: 
    path: "{{ maven_profile_location }}"
    mode: "0755"

- name: sleep 3s
  wait_for: timeout=3

- name: source maven.sh
  shell: ". {{ maven_profile_location }}"
  become: yes
  args:
    executable: /bin/bash
