---
#tasks file for elastic-role
- name: Elastic user
  user:
    name: elastic
    shell: /bin/false
    create_home: no
  
- name: import Elastic GPG Key
  become: yes
  command: "rpm --import {{ url_elastic_gpg_key }}"

- name: fetch Elastic repository
  yum_repository:
    name: elasticsearch
    description: elastic repo
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: install Elastic
  yum: 
    name: elasticsearch

- name: reload daemon
  become: yes
  command: /bin/systemctl daemon-reload

- name: launch and enable Elastic
  become: yes
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
