---
- name: Provision developper ubuntu machines
  hosts: dev
  become: yes
  roles:
  - role: git-role
  - role: maven-role
  tasks:
  - name: installing java
    include: task-java.yml
   
  - name: installing nano
     apt:
      name: 
      - nano
      state: latest
